source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'KeyboardManagerDemo' do
  pod 'CocoaLumberjack', '~> 3.5'
  pod 'ADUtils', '~>9.2'
  pod 'ADKeyboardManager', :path => '../'
  pod 'SwiftLint', '~> 0.38'
end

target 'KeyboardManagerDemoTests' do
  pod 'CocoaLumberjack', '~> 3.5'
  pod 'ADUtils', '~>9.2'
  pod 'ADKeyboardManager', :path => '../'
  pod 'SwiftLint', '~> 0.38'
end
