name: CI

on: [pull_request]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.6
        bundler-cache: true

    - name: Pods cache
      uses: actions/cache@v2
      with:
        path: ./KeyboardManagerDemo/Pods
        key: ${{ runner.os }}-cocoapods-${{ hashFiles('**/Podfile.lock') }}

    - name: Pod install
      working-directory: ./KeyboardManagerDemo
      run: bundle exec pod install

    - name: Build and test
      env:
        GITHUB_API_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_CI }}
      run: bundle exec fastlane ci_check
