name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bundle install
      working-directory: ./KeyboardManagerDemo
      run: bundle install
    - name: Pod install
      working-directory: ./KeyboardManagerDemo
      run: bundle exec pod install
    - name: Build and test
      working-directory: ./KeyboardManagerDemo
      run: bundle exec fastlane tests
    - name: Swiftlint
      working-directory: ./KeyboardManagerDemo
      run: bundle exec fastlane lint
    - name: Pod lib lint
      run: pod lib lint --allow-warnings